---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for Fedora
    ansible.builtin.package:
      update_only: yes
      update_cache: yes
      use: "{{ 'dnf' if ansible_distribution == 'Fedora' else omit }}"
    when: ansible_distribution == "Fedora"

  - name: install updates for Ubuntu
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache on web servers
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:
  - name: install mariadb on db servers
    ansible.builtin.package:
      name: mariadb
      state: latest
      use: "{{ 'dnf' if ansible_distribution == 'Fedora' else omit }}"
    when: ansible_distribution == "Fedora"
